### ISSUE TITLE
download and unbox error

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-box#3]
I was following the instructions on https://www.trufflesuite.com/boxes/harmony-box

However, I hit the following errors.  

```bash
$ truffle unbox harmony

Starting unbox...
=================

✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
Error: Truffle Box at URL https://github.com:truffle-box/harmony-box doesn't exist. If you believe this is an error, please contact Truffle support.
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:38:1)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:5:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Truffle v5.1.37 (core: 5.1.37)
Node v12.18.3


$ truffle unbox harmony-one/harmony-box

Starting unbox...
=================

✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/download/node_modules/got/index.js:482:1)
    at EventEmitter.emit (events.js:315:20)
    at getResponse (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/download/node_modules/got/index.js:320:1)
    at Immediate.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/download/node_modules/got/index.js:147:1)
    at processImmediate (internal/timers.js:456:21)
Truffle v5.1.37 (core: 5.1.37)
Node v12.18.3
```

**Comment by Severino** [comment]
Got the same error. Did you find a solution?

**Comment by Severino** [comment]
I followed the directions on truffle's harmony-box site. But the readme states:
```
(Until the box has been approved by Truffle you have to rely on the git installation step below)
```

So I think for the time beeing you must clone the repo and set it up manually.
This worked for me so far.
